# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {1}  -id {Project 1-311}  -string {{CRITICAL WARNING: [Project 1-311] Could not find the file 'C:/Users/Desktop/FSMD_microphone_tb_behav.wcfg', nor could it be found using path 'C:/Users/vicpt/Desktop/FSMD_microphone_tb_behav.wcfg'.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/package_dsed.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/pwm.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/en_4_cycles.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/imports/new/FSMD_microphone.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/audio_interface.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/controlador.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/fir_filter.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/mult.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/sum.vhd
  C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/new/dsed_audio.vhd
}
read_ip -quiet C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/vicpt/Documents/GitHub/proyect/final_project/final_project.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dsed_audio -part xc7a100tcsg324-1


write_checkpoint -force -noxdef dsed_audio.dcp

catch { report_utilization -file dsed_audio_utilization_synth.rpt -pb dsed_audio_utilization_synth.pb }
